/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JOptionPane;

/**
 *
 * @author Frankie
 */
public class Honoraries extends javax.swing.JInternalFrame {

    Principal principal;
    public Honoraries(Principal p) {
        initComponents();
        this.principal = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_monto = new javax.swing.JTextField();
        cmb_retencion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmb_metodo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btn_calcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_resultado = new javax.swing.JTextArea();
        btn_cerrar = new javax.swing.JButton();

        jLabel1.setText("Monto");

        txt_monto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_monto.setText("0");

        cmb_retencion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10.00%", "10.75%", "11.50%" }));
        cmb_retencion.setSelectedIndex(2);

        jLabel2.setText("Retencion");

        cmb_metodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Liquido", "Bruto" }));

        jLabel3.setText("Método");

        btn_calcular.setText("Calcular");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        txt_resultado.setColumns(20);
        txt_resultado.setLineWrap(true);
        txt_resultado.setRows(5);
        txt_resultado.setText("Ingrese el valor y elija las opciones para calcular su boleta de honorarios");
        jScrollPane1.setViewportView(txt_resultado);

        btn_cerrar.setText("Cerrar");
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_calcular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(65, 65, 65)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmb_retencion, 0, 197, Short.MAX_VALUE)
                                .addComponent(txt_monto)
                                .addComponent(cmb_metodo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(btn_cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_metodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_retencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_calcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_cerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        // Validar que los campos estén completos
        if(Integer.parseInt(this.txt_monto.getText()) == 0){
            JOptionPane.showMessageDialog(this, "Ingrese un número mayor que 0", "Valor no definido", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Captura el tipo de retención y generar las opciones de cálculo
        String retencion = this.cmb_retencion.getSelectedItem().toString();
        // Caputra el método de resultado (liqudo o bruto)
        String metodo = this.cmb_metodo.getSelectedItem().toString();
        double bruto, neto, valor_retencion;
        //Transformamos el % de retencion a un valor decimal
        double porc_retencion = 0;
        switch(retencion){
            case "10.00%":
                porc_retencion = 0.1;
                break;
            case "10.75%":
                porc_retencion = 0.1075;
                break;
            case "11.50%":
                porc_retencion = 0.1150;
                break;
            default: 
                porc_retencion = 0;
                break;
        }
        if(metodo.equals("Liquido")){
            neto = Double.parseDouble(this.txt_monto.getText());
            valor_retencion = neto * porc_retencion;
            bruto = neto + valor_retencion;
        } else {
            bruto = Double.parseDouble(this.txt_monto.getText());
            neto = bruto / (porc_retencion + 1);
            valor_retencion = bruto - neto;
        }
        //Ajustamos los valores a enteros
        neto = Math.round(neto);
        bruto = Math.round(bruto);
        valor_retencion = Math.round(valor_retencion);
        //Preparamos el mensaje
        String mensaje = "La boleta deberá realizarse con los siguiente datos:\n";
        mensaje += "Neto                     :$"+String.valueOf(neto)+"\n";
        mensaje += "Retención ("+retencion+"):$"+String.valueOf(valor_retencion)+"\n";
        mensaje += "Bruto                    :$"+String.valueOf(bruto)+"\n";
        //Mostrar el mensaje de resultado 
        this.txt_resultado.setText(mensaje);
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        this.setVisible(false);
        this.principal.enableMenu(true);
    }//GEN-LAST:event_btn_cerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JComboBox<String> cmb_metodo;
    private javax.swing.JComboBox<String> cmb_retencion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_monto;
    private javax.swing.JTextArea txt_resultado;
    // End of variables declaration//GEN-END:variables
}
