/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author Frankie
 */
public final class Principal extends javax.swing.JFrame {

    Dimension desktopSize;
    Dimension childSize;
    Login login;
    public Principal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.desktopSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.openLogin();
        
        
    }
    
    public void enableMenu(boolean b){
        this.mi_aplicacion.setEnabled(b);
        this.mi_rrhh.setEnabled(b);
        this.mi_bodega.setEnabled(b);
        this.mi_ventas.setEnabled(b);
        this.mi_mantenedores.setEnabled(b);
    }
    
 
    
    public void openLogin(){
        login = new Login(this);
        this.setCenterWindow(login);
        this.dkp_panel.add(login);
        login.setVisible(true);
    }
    
    public void showLogin(boolean b){
        this.login.setVisible(b);
    }
    
    public void openEmpleadoAgregar(EmpleadosAdmin ed){
        EmpleadosAgregar ea = new EmpleadosAgregar(ed);
        this.setCenterWindow(ea);
        this.dkp_panel.add(ea);
        ed.setVisible(false);
        ea.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        dkp_panel = new javax.swing.JDesktopPane();
        mb_menu = new javax.swing.JMenuBar();
        mi_aplicacion = new javax.swing.JMenu();
        mi_config = new javax.swing.JMenuItem();
        mi_cerrarsesion = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mi_salir = new javax.swing.JMenuItem();
        mi_rrhh = new javax.swing.JMenu();
        mi_honorarios = new javax.swing.JMenuItem();
        mi_liquidacion = new javax.swing.JMenuItem();
        mi_ventas = new javax.swing.JMenu();
        mi_generar_venta = new javax.swing.JMenuItem();
        mi_reimpresion = new javax.swing.JMenuItem();
        mi_bodega = new javax.swing.JMenu();
        mi_movimiento = new javax.swing.JMenuItem();
        mi_merma = new javax.swing.JMenuItem();
        mi_inventario = new javax.swing.JMenuItem();
        mi_mantenedores = new javax.swing.JMenu();
        mi_man_empresas = new javax.swing.JMenuItem();
        mi_man_empleados = new javax.swing.JMenuItem();
        mi_man_productos = new javax.swing.JMenuItem();
        mi_man_usuarios = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicacación Maestro Detalle");

        javax.swing.GroupLayout dkp_panelLayout = new javax.swing.GroupLayout(dkp_panel);
        dkp_panel.setLayout(dkp_panelLayout);
        dkp_panelLayout.setHorizontalGroup(
            dkp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dkp_panelLayout.setVerticalGroup(
            dkp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        mi_aplicacion.setText("Aplicación");
        mi_aplicacion.setEnabled(false);

        mi_config.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mi_config.setText("Configuración");
        mi_config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_configActionPerformed(evt);
            }
        });
        mi_aplicacion.add(mi_config);

        mi_cerrarsesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mi_cerrarsesion.setText("Cerrar Sesión");
        mi_cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_cerrarsesionActionPerformed(evt);
            }
        });
        mi_aplicacion.add(mi_cerrarsesion);
        mi_aplicacion.add(jSeparator1);

        mi_salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mi_salir.setText("Salir");
        mi_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_salirActionPerformed(evt);
            }
        });
        mi_aplicacion.add(mi_salir);

        mb_menu.add(mi_aplicacion);

        mi_rrhh.setText("RR.HH.");
        mi_rrhh.setEnabled(false);

        mi_honorarios.setText("Calculo Honorarios");
        mi_honorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_honorariosActionPerformed(evt);
            }
        });
        mi_rrhh.add(mi_honorarios);

        mi_liquidacion.setText("Liquidacion de Sueldos");
        mi_rrhh.add(mi_liquidacion);

        mb_menu.add(mi_rrhh);

        mi_ventas.setText("Ventas");
        mi_ventas.setEnabled(false);

        mi_generar_venta.setText("Generar Venta");
        mi_ventas.add(mi_generar_venta);

        mi_reimpresion.setText("Reimprimir Boleta / Factura");
        mi_ventas.add(mi_reimpresion);

        mb_menu.add(mi_ventas);

        mi_bodega.setText("Bodega");
        mi_bodega.setEnabled(false);

        mi_movimiento.setText("Registrar Movimiento");
        mi_bodega.add(mi_movimiento);

        mi_merma.setText("Registrar Merma");
        mi_bodega.add(mi_merma);

        mi_inventario.setText("Obtener Inventario");
        mi_bodega.add(mi_inventario);

        mb_menu.add(mi_bodega);

        mi_mantenedores.setText("Mantenedores");
        mi_mantenedores.setEnabled(false);

        mi_man_empresas.setText("Empresas");
        mi_mantenedores.add(mi_man_empresas);

        mi_man_empleados.setText("Empleados");
        mi_man_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_man_empleadosActionPerformed(evt);
            }
        });
        mi_mantenedores.add(mi_man_empleados);

        mi_man_productos.setText("Productos");
        mi_mantenedores.add(mi_man_productos);

        mi_man_usuarios.setText("Usuarios");
        mi_mantenedores.add(mi_man_usuarios);

        mb_menu.add(mi_mantenedores);

        setJMenuBar(mb_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dkp_panel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dkp_panel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_cerrarsesionActionPerformed
        //Bloqueamos el menu
        this.enableMenu(false);
        //Abrimos el formulario de login otra
        this.showLogin(true);
    }//GEN-LAST:event_mi_cerrarsesionActionPerformed

    private void mi_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mi_salirActionPerformed

    private void mi_configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_configActionPerformed
        //Creamos una instancia del objeto Configuration
        Configuration config = new Configuration(this);
        this.setCenterWindow(config);
        this.dkp_panel.add(config);
        config.setVisible(true);
        this.enableMenu(false);
    }//GEN-LAST:event_mi_configActionPerformed

    private void mi_honorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_honorariosActionPerformed
        Honoraries hono = new Honoraries(this);
        this.setCenterWindow(hono);
        this.dkp_panel.add(hono);
        hono.setVisible(true);
        this.enableMenu(false);
    }//GEN-LAST:event_mi_honorariosActionPerformed

    private void mi_man_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_man_empleadosActionPerformed
        EmpleadosAdmin ea = new EmpleadosAdmin(this);
        this.setCenterWindow(ea);
        this.dkp_panel.add(ea);
        ea.setVisible(true);
        this.enableMenu(false);
    }//GEN-LAST:event_mi_man_empleadosActionPerformed

    private void setCenterWindow(javax.swing.JInternalFrame e){
        this.childSize = e.getSize();
        e.setLocation((this.desktopSize.width - this.childSize.width)/2, (this.desktopSize.height - (this.childSize.height + 100))/2);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dkp_panel;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar mb_menu;
    private javax.swing.JMenu mi_aplicacion;
    private javax.swing.JMenu mi_bodega;
    private javax.swing.JMenuItem mi_cerrarsesion;
    private javax.swing.JMenuItem mi_config;
    private javax.swing.JMenuItem mi_generar_venta;
    private javax.swing.JMenuItem mi_honorarios;
    private javax.swing.JMenuItem mi_inventario;
    private javax.swing.JMenuItem mi_liquidacion;
    private javax.swing.JMenuItem mi_man_empleados;
    private javax.swing.JMenuItem mi_man_empresas;
    private javax.swing.JMenuItem mi_man_productos;
    private javax.swing.JMenuItem mi_man_usuarios;
    private javax.swing.JMenu mi_mantenedores;
    private javax.swing.JMenuItem mi_merma;
    private javax.swing.JMenuItem mi_movimiento;
    private javax.swing.JMenuItem mi_reimpresion;
    private javax.swing.JMenu mi_rrhh;
    private javax.swing.JMenuItem mi_salir;
    private javax.swing.JMenu mi_ventas;
    // End of variables declaration//GEN-END:variables
}
