/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.util.HashMap;
import javax.swing.JOptionPane;
import models.Category;
import models.MeasurementUnity;
import models.Product;
import utils.Functions;

/**
 *
 * @author Frankie
 */
public class ProductosAgregar extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProductosAgregar
     */
    ProductosAdmin pa;
    Category categorias;
    MeasurementUnity unidadMedida;
    public ProductosAgregar(ProductosAdmin pa) {
        initComponents();
        this.pa = pa;
        this.categorias = new Category();
        this.unidadMedida = new MeasurementUnity();
        HashMap<String, Integer> categoriasList = this.categorias.getCategories();
        HashMap<String, Integer> unidadMedidaList = this.unidadMedida.getUList();
        for(String i: categoriasList.keySet()){
            this.cmb_categorias.addItem(i);
        }
        for(String i: unidadMedidaList.keySet()){
            this.cmb_unidades_medida.addItem(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nombres = new javax.swing.JLabel();
        lbl_departamento = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmb_categorias = new javax.swing.JComboBox<>();
        txt_codigo = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        lbl_run = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        cmb_unidades_medida = new javax.swing.JComboBox<>();
        lbl_departamento1 = new javax.swing.JLabel();
        lbl_id_categoria = new javax.swing.JLabel();
        lbl_id_unidad_medida = new javax.swing.JLabel();

        lbl_nombres.setText("Nombre");

        lbl_departamento.setText("Categoria");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nuevo Producto");

        cmb_categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_categoriasActionPerformed(evt);
            }
        });

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        lbl_run.setText("Código");

        cmb_unidades_medida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_unidades_medidaActionPerformed(evt);
            }
        });

        lbl_departamento1.setText("Unidad de Medida");

        lbl_id_categoria.setText("0");

        lbl_id_unidad_medida.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nombre)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_departamento)
                            .addComponent(cmb_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_departamento1)
                            .addComponent(cmb_unidades_medida, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombres)
                            .addComponent(jLabel1)
                            .addComponent(lbl_run)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_id_categoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_id_unidad_medida)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addComponent(lbl_run)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_id_categoria)
                        .addComponent(lbl_id_unidad_medida)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_nombres)
                .addGap(3, 3, 3)
                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_departamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_departamento1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_unidades_medida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(btn_cancelar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_categoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_categoriasActionPerformed
        HashMap<String, Integer> mapa = this.categorias.getCategories();
        this.lbl_id_categoria.setText(mapa.get(this.cmb_categorias.getSelectedItem().toString()).toString());
    }//GEN-LAST:event_cmb_categoriasActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        String errores = "";
        errores += this.txt_codigo.getText().length() < 6 || !Functions.isNumeric(this.txt_codigo.getText()) ? "- Ingrese código del producto.\n" : "";
        errores += this.cmb_categorias.toString() == "Seleccione" ? "- Seleccione una categoria." : "";
        errores += this.cmb_unidades_medida.toString() == "Seleccione" ? "- Seleccione una unidad de medida." : "";
        if(errores.length() > 0){
            JOptionPane.showMessageDialog(rootPane, "Corrija los errores:\n"+errores);
        } else {
            Product p = new Product(Integer.parseInt(this.txt_codigo.getText()), this.txt_nombre.getText(), Integer.parseInt(this.lbl_id_categoria.getText()), Integer.parseInt(this.lbl_id_unidad_medida.getText()));
            p.save();
            this.setVisible(false);
            this.pa.recargarProductos();
            this.pa.setVisible(true);
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.setVisible(false);
        this.pa.setVisible(true);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void cmb_unidades_medidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_unidades_medidaActionPerformed
        HashMap<String, Integer> mapa = this.unidadMedida.getUList();
        this.lbl_id_unidad_medida.setText(mapa.get(this.cmb_unidades_medida.getSelectedItem().toString()).toString());
    }//GEN-LAST:event_cmb_unidades_medidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JComboBox<String> cmb_categorias;
    private javax.swing.JComboBox<String> cmb_unidades_medida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_departamento;
    private javax.swing.JLabel lbl_departamento1;
    private javax.swing.JLabel lbl_id_categoria;
    private javax.swing.JLabel lbl_id_unidad_medida;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_run;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
